pip install --user matplotlib
pip install --user scipy==1.4.1
pip install --user scikit-learn
pip install --user pandas
pip install --user seaborn
pip install --user h5py
pip install --user argparse
pip install --user NuRadioMC
pip install --user NuRadioReco
pip install --user numpy==1.18.5
pip install --user tensorflow==2.3.0
pip install --user keras==2.4.3
